baseURL = "https://jalict.github.io/gizem-arici/"
languageCode = "en-us"
title = "Gizem Arici"
theme = "gizem-arici-theme"
publishDir = "docs/"

[imaging]
  [imaging.exif]
    disableDate = true
    disableLatLong = true
    excludeFields = ''
    includeFields = ''
